# Generated by Django 4.2 on 2023-08-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('pub_date', models.DateField(blank=True)),
                ('category', models.IntegerField(default=0)),
                ('pages', models.IntegerField(default=0)),
                ('book_text', models.CharField(blank=True, max_length=256)),
                ('pics_path', models.CharField(blank=True, max_length=256)),
                ('user_summary', models.TextField(blank=True)),
                ('user_review', models.IntegerField(default=0)),
                ('ins_date', models.DateField(auto_now=True)),
                ('upd_date', models.DateField(auto_now_add=True)),
                ('delete_flg', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'book_shelf',
            },
        ),
    ]
